/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AdminRouteImport } from './routes/_admin'
import { Route as AdminIndexRouteImport } from './routes/_admin/index'
import { Route as AdminUsersRouteImport } from './routes/_admin/users'
import { Route as AdminSignupLinksRouteImport } from './routes/_admin/signup-links'
import { Route as AdminServerSyncRouteImport } from './routes/_admin/server-sync'
import { Route as AdminProvidersRouteImport } from './routes/_admin/providers'
import { Route as AdminNotificationsRouteImport } from './routes/_admin/notifications'
import { Route as AdminMigrationRouteImport } from './routes/_admin/migration'
import { Route as AdminEmailRouteImport } from './routes/_admin/email'
import { Route as AdminCoversRouteImport } from './routes/_admin/covers'
import { Route as AdminServerSyncIndexRouteImport } from './routes/_admin/server-sync.index'
import { Route as AdminEmailIndexRouteImport } from './routes/_admin/email.index'
import { Route as AdminServerSyncSourceIdRouteImport } from './routes/_admin/server-sync.$sourceId'
import { Route as AdminEmailTemplatesRouteImport } from './routes/_admin/email.templates'

const AdminRoute = AdminRouteImport.update({
  id: '/_admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSignupLinksRoute = AdminSignupLinksRouteImport.update({
  id: '/signup-links',
  path: '/signup-links',
  getParentRoute: () => AdminRoute,
} as any)
const AdminServerSyncRoute = AdminServerSyncRouteImport.update({
  id: '/server-sync',
  path: '/server-sync',
  getParentRoute: () => AdminRoute,
} as any)
const AdminProvidersRoute = AdminProvidersRouteImport.update({
  id: '/providers',
  path: '/providers',
  getParentRoute: () => AdminRoute,
} as any)
const AdminNotificationsRoute = AdminNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => AdminRoute,
} as any)
const AdminMigrationRoute = AdminMigrationRouteImport.update({
  id: '/migration',
  path: '/migration',
  getParentRoute: () => AdminRoute,
} as any)
const AdminEmailRoute = AdminEmailRouteImport.update({
  id: '/email',
  path: '/email',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCoversRoute = AdminCoversRouteImport.update({
  id: '/covers',
  path: '/covers',
  getParentRoute: () => AdminRoute,
} as any)
const AdminServerSyncIndexRoute = AdminServerSyncIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminServerSyncRoute,
} as any)
const AdminEmailIndexRoute = AdminEmailIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminEmailRoute,
} as any)
const AdminServerSyncSourceIdRoute = AdminServerSyncSourceIdRouteImport.update({
  id: '/$sourceId',
  path: '/$sourceId',
  getParentRoute: () => AdminServerSyncRoute,
} as any)
const AdminEmailTemplatesRoute = AdminEmailTemplatesRouteImport.update({
  id: '/templates',
  path: '/templates',
  getParentRoute: () => AdminEmailRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AdminIndexRoute
  '/covers': typeof AdminCoversRoute
  '/email': typeof AdminEmailRouteWithChildren
  '/migration': typeof AdminMigrationRoute
  '/notifications': typeof AdminNotificationsRoute
  '/providers': typeof AdminProvidersRoute
  '/server-sync': typeof AdminServerSyncRouteWithChildren
  '/signup-links': typeof AdminSignupLinksRoute
  '/users': typeof AdminUsersRoute
  '/email/templates': typeof AdminEmailTemplatesRoute
  '/server-sync/$sourceId': typeof AdminServerSyncSourceIdRoute
  '/email/': typeof AdminEmailIndexRoute
  '/server-sync/': typeof AdminServerSyncIndexRoute
}
export interface FileRoutesByTo {
  '/covers': typeof AdminCoversRoute
  '/migration': typeof AdminMigrationRoute
  '/notifications': typeof AdminNotificationsRoute
  '/providers': typeof AdminProvidersRoute
  '/signup-links': typeof AdminSignupLinksRoute
  '/users': typeof AdminUsersRoute
  '/': typeof AdminIndexRoute
  '/email/templates': typeof AdminEmailTemplatesRoute
  '/server-sync/$sourceId': typeof AdminServerSyncSourceIdRoute
  '/email': typeof AdminEmailIndexRoute
  '/server-sync': typeof AdminServerSyncIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_admin': typeof AdminRouteWithChildren
  '/_admin/covers': typeof AdminCoversRoute
  '/_admin/email': typeof AdminEmailRouteWithChildren
  '/_admin/migration': typeof AdminMigrationRoute
  '/_admin/notifications': typeof AdminNotificationsRoute
  '/_admin/providers': typeof AdminProvidersRoute
  '/_admin/server-sync': typeof AdminServerSyncRouteWithChildren
  '/_admin/signup-links': typeof AdminSignupLinksRoute
  '/_admin/users': typeof AdminUsersRoute
  '/_admin/': typeof AdminIndexRoute
  '/_admin/email/templates': typeof AdminEmailTemplatesRoute
  '/_admin/server-sync/$sourceId': typeof AdminServerSyncSourceIdRoute
  '/_admin/email/': typeof AdminEmailIndexRoute
  '/_admin/server-sync/': typeof AdminServerSyncIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/covers'
    | '/email'
    | '/migration'
    | '/notifications'
    | '/providers'
    | '/server-sync'
    | '/signup-links'
    | '/users'
    | '/email/templates'
    | '/server-sync/$sourceId'
    | '/email/'
    | '/server-sync/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/covers'
    | '/migration'
    | '/notifications'
    | '/providers'
    | '/signup-links'
    | '/users'
    | '/'
    | '/email/templates'
    | '/server-sync/$sourceId'
    | '/email'
    | '/server-sync'
  id:
    | '__root__'
    | '/_admin'
    | '/_admin/covers'
    | '/_admin/email'
    | '/_admin/migration'
    | '/_admin/notifications'
    | '/_admin/providers'
    | '/_admin/server-sync'
    | '/_admin/signup-links'
    | '/_admin/users'
    | '/_admin/'
    | '/_admin/email/templates'
    | '/_admin/server-sync/$sourceId'
    | '/_admin/email/'
    | '/_admin/server-sync/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AdminRoute: typeof AdminRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_admin': {
      id: '/_admin'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_admin/': {
      id: '/_admin/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/users': {
      id: '/_admin/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/signup-links': {
      id: '/_admin/signup-links'
      path: '/signup-links'
      fullPath: '/signup-links'
      preLoaderRoute: typeof AdminSignupLinksRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/server-sync': {
      id: '/_admin/server-sync'
      path: '/server-sync'
      fullPath: '/server-sync'
      preLoaderRoute: typeof AdminServerSyncRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/providers': {
      id: '/_admin/providers'
      path: '/providers'
      fullPath: '/providers'
      preLoaderRoute: typeof AdminProvidersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/notifications': {
      id: '/_admin/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof AdminNotificationsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/migration': {
      id: '/_admin/migration'
      path: '/migration'
      fullPath: '/migration'
      preLoaderRoute: typeof AdminMigrationRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/email': {
      id: '/_admin/email'
      path: '/email'
      fullPath: '/email'
      preLoaderRoute: typeof AdminEmailRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/covers': {
      id: '/_admin/covers'
      path: '/covers'
      fullPath: '/covers'
      preLoaderRoute: typeof AdminCoversRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/server-sync/': {
      id: '/_admin/server-sync/'
      path: '/'
      fullPath: '/server-sync/'
      preLoaderRoute: typeof AdminServerSyncIndexRouteImport
      parentRoute: typeof AdminServerSyncRoute
    }
    '/_admin/email/': {
      id: '/_admin/email/'
      path: '/'
      fullPath: '/email/'
      preLoaderRoute: typeof AdminEmailIndexRouteImport
      parentRoute: typeof AdminEmailRoute
    }
    '/_admin/server-sync/$sourceId': {
      id: '/_admin/server-sync/$sourceId'
      path: '/$sourceId'
      fullPath: '/server-sync/$sourceId'
      preLoaderRoute: typeof AdminServerSyncSourceIdRouteImport
      parentRoute: typeof AdminServerSyncRoute
    }
    '/_admin/email/templates': {
      id: '/_admin/email/templates'
      path: '/templates'
      fullPath: '/email/templates'
      preLoaderRoute: typeof AdminEmailTemplatesRouteImport
      parentRoute: typeof AdminEmailRoute
    }
  }
}

interface AdminEmailRouteChildren {
  AdminEmailTemplatesRoute: typeof AdminEmailTemplatesRoute
  AdminEmailIndexRoute: typeof AdminEmailIndexRoute
}

const AdminEmailRouteChildren: AdminEmailRouteChildren = {
  AdminEmailTemplatesRoute: AdminEmailTemplatesRoute,
  AdminEmailIndexRoute: AdminEmailIndexRoute,
}

const AdminEmailRouteWithChildren = AdminEmailRoute._addFileChildren(
  AdminEmailRouteChildren,
)

interface AdminServerSyncRouteChildren {
  AdminServerSyncSourceIdRoute: typeof AdminServerSyncSourceIdRoute
  AdminServerSyncIndexRoute: typeof AdminServerSyncIndexRoute
}

const AdminServerSyncRouteChildren: AdminServerSyncRouteChildren = {
  AdminServerSyncSourceIdRoute: AdminServerSyncSourceIdRoute,
  AdminServerSyncIndexRoute: AdminServerSyncIndexRoute,
}

const AdminServerSyncRouteWithChildren = AdminServerSyncRoute._addFileChildren(
  AdminServerSyncRouteChildren,
)

interface AdminRouteChildren {
  AdminCoversRoute: typeof AdminCoversRoute
  AdminEmailRoute: typeof AdminEmailRouteWithChildren
  AdminMigrationRoute: typeof AdminMigrationRoute
  AdminNotificationsRoute: typeof AdminNotificationsRoute
  AdminProvidersRoute: typeof AdminProvidersRoute
  AdminServerSyncRoute: typeof AdminServerSyncRouteWithChildren
  AdminSignupLinksRoute: typeof AdminSignupLinksRoute
  AdminUsersRoute: typeof AdminUsersRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminCoversRoute: AdminCoversRoute,
  AdminEmailRoute: AdminEmailRouteWithChildren,
  AdminMigrationRoute: AdminMigrationRoute,
  AdminNotificationsRoute: AdminNotificationsRoute,
  AdminProvidersRoute: AdminProvidersRoute,
  AdminServerSyncRoute: AdminServerSyncRouteWithChildren,
  AdminSignupLinksRoute: AdminSignupLinksRoute,
  AdminUsersRoute: AdminUsersRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AdminRoute: AdminRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
