services:
  couchdb:
    build:
      context: ./apps/couchdb
      dockerfile: Dockerfile
    restart: always
    ports:
      - "5984:5984"
    environment:
      - COUCHDB_USER=${COUCHDB_USER}
      - COUCHDB_PASSWORD=${COUCHDB_PASSWORD}
    volumes:
        - ./.data/dbdata:/opt/couchdb/data

  api:
    build:
      context: ./apps/api
      dockerfile: Dockerfile
      target: production
    restart: always
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - COUCHDB_URL=http://${COUCHDB_USER}:${COUCHDB_PASSWORD}@couchdb:5984
      # covers bucket 
      - COVERS_BUCKET_NAME=${COVERS_BUCKET_NAME}
      - COVERS_PLACEHOLDER_BUCKET_KEY=${COVERS_PLACEHOLDER_BUCKET_KEY}
      # AWS Authentication
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}