services:
  api:
    extends:
      file: docker-compose.yml
      service: api
    environment:
      - NODE_ENV=development
    restart: unless-stopped
    volumes:
      - ./apps/api:/usr/src/app
      - /usr/src/app/node_modules
    command: npm run start:dev
