services:
  # couchdb:
  #   build:
  #     context: ./apps/couchdb
  #     dockerfile: dockerfile
  #   restart: always
  #   ports:
  #     - "5984:5984"
  #   environment:
  #     - COUCHDB_USER=${COUCHDB_USER}
  #     - COUCHDB_PASSWORD=${COUCHDB_PASSWORD}
  #   volumes:
  #       - ./.data/dbdata:/opt/couchdb/data

  api:
    build:
      context: ./
      dockerfile: dockerfile
      target: api
    restart: always
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - COUCH_DB_URL=${COUCH_DB_URL}
      - COVERS_BUCKET_NAME=${COVERS_BUCKET_NAME}
      - COVERS_PLACEHOLDER_BUCKET_KEY=${COVERS_PLACEHOLDER_BUCKET_KEY}
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - COUCHDB_USER=${COUCHDB_USER}
      - COUCHDB_PASSWORD=${COUCHDB_PASSWORD}
      - STAGE=${STAGE}
      - CONTACT_TO_ADDRESS=${CONTACT_TO_ADDRESS}
      - AWS_API_URI=${AWS_API_URI}
      - SUPABASE_SERVICE_ROLE_KEY=${SUPABASE_SERVICE_ROLE_KEY}
      - SUPABASE_PROJECT_URL=${SUPABASE_PROJECT_URL}
      - FIREBASE_CONFIG=${FIREBASE_CONFIG}
