services:
  couchdb:
    extends:
      file: docker-compose.yml
      service: couchdb
    build:
      context: ./
      dockerfile: dockerfile
      target: couchdb

  postgres:
    extends:
      file: docker-compose.yml
      service: postgres
    ports:
      - "5432:5432"

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@oboku.dev
      PGADMIN_DEFAULT_PASSWORD: password
    ports:
      - "5050:80"
    volumes:
      - oboku-pgadmin:/var/lib/pgadmin

  web:
    extends:
      file: docker-compose.yml
      service: web
    build:
      context: ./
      dockerfile: dockerfile
      target: web

  admin:
    extends:
      file: docker-compose.yml
      service: admin
    build:
      context: ./
      dockerfile: dockerfile
      target: admin

  api:
    extends:
      file: docker-compose.yml
      service: api
    build:
      context: ./
      dockerfile: dockerfile
      target: api
    environment:
      - NODE_ENV=development
    restart: unless-stopped
    volumes:
      - ./apps/api:/usr/src/app
    command: npm run start:dev

volumes:
  oboku-postgres:
  oboku-pgadmin:
  oboku-couchdb-data:
  oboku-couchdb-config:
  oboku-api-data:
