services:
  # couchdb:
  #   extends:
  #     file: docker-compose.yml
  #     service: couchdb

  postgres:
    extends:
      file: docker-compose.yml
      service: postgres
    volumes:
      - ./.data/postgres/data:/var/lib/postgresql/data

  api:
    extends:
      file: docker-compose.yml
      service: api
    build:
      context: ./
      dockerfile: dockerfile
      target: api
    environment:
      - NODE_ENV=development
    restart: unless-stopped
    volumes:
      - ./apps/api:/usr/src/app
      - /usr/src/app/node_modules
    command: npm run start:dev