services:
  couchdb:
    build:
      context: ./
      dockerfile: dockerfile
      target: couchdb
    restart: always
    ports:
      - "5984:5984"
      # extra binds used for http/1 load balancing
      - "5985:5984"
      - "5986:5984"
    env_file:
      - .env
    environment:
      - COUCHDB_USER=admin
      - JWT_PRIVATE_KEY_FILE=/secrets/jwt_private_key.pem
      - JWT_PUBLIC_KEY_FILE=/secrets/jwt_public_key.pem
    volumes:
      - ./secrets:/secrets
      - oboku-couchdb-data:/opt/couchdb/data
      - oboku-couchdb-config:/opt/couchdb/etc/local.d

  postgres:
    image: postgres
    restart: always
    env_file:
      - .env
    environment:
      POSTGRES_DB: oboku
    volumes:
      - oboku-postgres:/var/lib/postgresql/data

  web:
    build:
      context: ./
      dockerfile: dockerfile
      target: web
    restart: always
    ports:
      - "80:80"

  api:
    build:
      context: ./
      dockerfile: dockerfile
      target: api
    restart: always
    ports:
      - "3000:3000"
    env_file:
      - .env
    environment:
      - NODE_ENV=production
      - JWT_PRIVATE_KEY_FILE=/secrets/jwt_private_key.pem
      - JWT_PUBLIC_KEY_FILE=/secrets/jwt_public_key.pem
    volumes:
      - ./secrets:/secrets
      - oboku-api-data:/var/lib/oboku/data

volumes:
  oboku-postgres:
  oboku-couchdb-data:
  oboku-couchdb-config:
  oboku-api-data:
