version: '3.1'

services:

  oboku-server:
    image: oboku-server
    restart: always
    ports:
      - "443:443"
    volumes:
      - /opt/oboku/etc/data:/opt/oboku/etc/data
      - /opt/oboku/etc/tmp:/opt/oboku/etc/tmp