version: '3.1'

services:

  couchdb:
    image: couchdb
    restart: always
    ports:
      - "5984:5984"
      - "5986:5986"
    volumes:
      - /private/couchdb/local.d:/opt/couchdb/etc/local.d
  nginx: 
    image: nginx:latest
    container_name: production_nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./.secrets/:/etc/letsencrypt/
    ports:
      - 4003:4003
      - 4000:4000

