services:
  couchdb:
    image: couchdb:latest
    restart: always
    ports:
      - "5984:5984"
    env_file:
      - .env
    volumes:
      - oboku-couchdb:/opt/couchdb/data

  postgres:
    image: postgres
    restart: always
    env_file:
      - .env
    environment:
      POSTGRES_DB: oboku
    volumes:
      - oboku-postgres:/var/lib/postgresql/data

  web:
    build:
      context: ./
      dockerfile: dockerfile
      target: web
    restart: always
    ports:
      - "80:80"

  api:
    build:
      context: ./
      dockerfile: dockerfile
      target: api
    restart: always
    ports:
      - "3000:3000"
    env_file:
      - .env
      - NODE_ENV=production
      # will connect through the postgres service name docker bridge network
      - POSTGRES_HOST=postgres

volumes:
  oboku-postgres:
  oboku-couchdb:
