import type { AWS } from '@serverless/typescript';
import covers from '@functions/covers';
import signin from '@functions/signin';
import signup from '@functions/signup';
import requestAccess from '@functions/requestAccess';
import refreshMetadata from '@functions/refreshMetadata';
import refreshMetadataLongProcess from '@functions/refreshMetadataLongProcess';
import syncDataSource from '@functions/syncDataSource';
import syncDataSourceLongProcess from '@functions/syncDataSourceLongProcess';
import corsProxy from '@functions/corsProxy';
import { getCommon } from './serverlessHelpers';

const functions: AWS[`functions`] = {
  covers,
  signin,
  signup,
  requestAccess,
  refreshMetadata,
  refreshMetadataLongProcess,
  syncDataSource,
  syncDataSourceLongProcess,
  cors: corsProxy
}

Object.keys(functions).forEach((key) => {
  const fn = functions[key as keyof typeof functions]

  // dynamically add common layer to all functions
  fn[`layers`] = [...(fn[`layers`] ?? []),
  // Ref name is generated by TitleCasing the layer name & appending LambdaLayer
  { Ref: "CommonLibsLambdaLayer" }
  ]
})

const serverlessConfiguration: AWS = {
  ...getCommon(),
  plugins: ['serverless-offline', 'serverless-bundle'],
  provider: {
    name: 'aws',
    runtime: 'nodejs14.x',
    timeout: 30, //  30 seconds
    apiGateway: {
      minimumCompressionSize: 1024,
      shouldStartNameWithService: true,
      binaryMediaTypes: [`*/*`]
    },
    // Do this if you want to load env vars into the Serverless environment AND
    // automatically configure all your functions with them.
    // This is usually not recommended to avoid loading secrets by accident (e.g. AWS_SECRET_ACCESS_KEY)
    environment: {
      AWS_NODEJS_CONNECTION_REUSE_ENABLED: '1',
      NODE_OPTIONS: '--enable-source-maps --stack-trace-limit=1000',
      STAGE: '${sls:stage}',
      COUCH_DB_URL: '${env:COUCH_DB_URL}',
      CONTACT_TO_ADDRESS: '${env:CONTACT_TO_ADDRESS}',
      AWS_API_URI: '${env:AWS_API_URI}',
      GOOGLE_BOOK_API_URL: '${env:GOOGLE_BOOK_API_URL}',
      OFFLINE: '${env:OFFLINE}',
    },
  },
  layers: {
    // sharp: {
    //   name: "${sls:stage}-sharp",
    //   path: `layers/SharpLayer`, // required, path to layer contents on disk
    //   description: `sharp@0.30.3`,
    //   package: {
    //     include: [`node_modules/**`]
    //   },
    // }
    "commonLibs": {
      "path": "layers",
      "name": "commonLibs",
      "description": "Common big dependencies",
      // "compatibleRuntimes": [
      //   "python3.8"
      // ],
      // "compatibleArchitectures": [
      //   "x86_64",
      //   "arm64"
      // ],
      // "licenseInfo": "GPLv3",
      "retain": false
    }
  },
  // import the function via paths
  functions,
  resources: {
    Resources: {
      // @see https://www.serverless.com/framework/docs/providers/aws/guide/iam#custom-iam-roles
      lambdaDefault: {
        Type: `AWS::IAM::Role`,
        Properties: {
          RoleName: "${self:service}-${sls:stage}-${aws:region}-lambda-default",
          // required if you want to use 'serverless deploy --function' later on
          AssumeRolePolicyDocument: {
            Version: '2012-10-17',
            Statement: [{ Effect: "Allow", Principal: { Service: [`lambda.amazonaws.com`] }, Action: "sts:AssumeRole" }]
          },
          Policies: [{
            PolicyName: "${self:service}-${sls:stage}-${aws:region}-lambda-default-policy",
            PolicyDocument: {
              Statement: [
                // note that these rights are given in the default policy and are required if you want logs out of your lambda(s)
                {
                  Effect: `Allow`,
                  Action: [
                    `logs:CreateLogGroup`,
                    `logs:CreateLogStream`,
                    `logs:PutLogEvents`,
                  ],
                  Resource: [
                    {
                      "Fn::Join": [
                        ":",
                        [
                          "arn:aws:logs",
                          {
                            "Ref": "AWS::Region"
                          },
                          {
                            "Ref": "AWS::AccountId"
                          },
                          "log-group:/aws/lambda/${self:service}-${sls:stage}*:*:*"
                        ]
                      ]
                    }
                  ],
                },
                {
                  "Effect": "Allow",
                  "Action": [
                    "s3:GetObject",
                    "s3:ListBucket",
                    "s3:GetBucketLocation",
                    "s3:GetObjectVersion",
                    "s3:GetLifecycleConfiguration",
                    "s3:PutObject",
                    "s3:PutObjectAcl"
                  ],
                  "Resource": [
                    "arn:aws:s3:::oboku-covers",
                    "arn:aws:s3:::oboku-covers/*"
                  ],
                },
                {
                  "Effect": "Allow",
                  "Action": [
                    "lambda:InvokeFunction",
                  ],
                  "Resource": [
                    "arn:aws:lambda:${aws:region}:*:function:${self:service}-${sls:stage}*",
                  ],
                },
                // this is needed to read from ssm and retrieve secrets
                {
                  Effect: `Allow`,
                  Action: [
                    `ssm:GetParameter`
                  ],
                  Resource: [
                    {
                      "Fn::Join": [
                        ":",
                        [
                          "arn:aws:ssm",
                          {
                            "Ref": "AWS::Region"
                          },
                          {
                            "Ref": "AWS::AccountId"
                          },
                          "parameter/*"
                        ]
                      ]
                    }
                  ],
                }
              ]
            }
          }]
        }
      }
    }
  },
  package: { individually: true },
  custom: {
    bundle:
    {
      // These are packages that need to be included in the Lambda package (the .zip file that's sent to AWS). 
      // But they are not compatible with Webpack. So they are marked as externals to tell Webpack not bundle them.
      externals: [
        "knex",
        "sharp",
        `aws-sdk`,
        `aws-lambda`,
        `nano`,
        `yup`,
        `crypto-js`,
        /^@oboku\/.+$/,
        /^@middy\/.+$/,
        `dropbox`
      ],
      packagerOptions:
      {
        scripts: [
          `rm -rf node_modules/sharp && SHARP_IGNORE_GLOBAL_LIBVIPS=1 npm install --arch=x64 --platform=linux sharp`,
        ]
      }
    }
  },
};

module.exports = serverlessConfiguration;
