export const ROUTES = {
  HOME: "/",
  BOOK_DETAILS: "/book/:id",
  COLLECTION_DETAILS: "/collections/:id",
  PROFILE: "/profile",
  SECURITY: "/profile/security",
  SETTINGS: "/profile/settings",
  STATISTICS: "/profile/statistics",
  PLUGINS: "/plugins",
  PLUGINS_TYPE: "/plugins/:type",
  DATASOURCES: "/sync",
  DATASOURCES_LIST: "/sync/datasources",
  DATASOURCES_REPORTS: "/sync/reports",
  LIBRARY_ROOT: "/library",
  LIBRARY_BOOKS: "/library/books",
  LIBRARY_COLLECTIONS: "/library/collections",
  LIBRARY_SERIES: "/library/series",
  LIBRARY_TAGS: "/library/tags",
  LOGIN: "/login",
  SIGN_UP: "/signup",
  AUTH_CALLBACK: "/auth_callback",
  READER: "/reader/:id",
  SEARCH: "/search",
  PROBLEMS: "/problems",
} as const
