const BOOKS_ROOT = "/books"

export const ROUTES = {
  HOME: "/",
  BOOK_DETAILS: `${BOOKS_ROOT}/:id`,
  BOOK_TAGS: `${BOOKS_ROOT}/:id/tags`,
  BOOK_COLLECTIONS: `${BOOKS_ROOT}/:id/collections`,
  COLLECTION_DETAILS: "/collections/:id",
  PROFILE: "/profile",
  NOTIFICATIONS: "/profile/notifications",
  SECURITY: "/profile/security",
  SECRETS: "/profile/secrets",
  SETTINGS: "/profile/settings",
  STATISTICS: "/profile/statistics",
  PLUGINS: "/plugins",
  PLUGINS_TYPE: "/plugins/:type",
  PLUGINS_CONNECTORS_NEW: "/plugins/:type/connectors/new",
  PLUGINS_CONNECTORS_EDIT: "/plugins/:type/connectors/:id",
  SYNC: "/sync",
  SYNC_DATASOURCES: "/sync/datasources",
  SYNC_NEW_DATASOURCES: "/sync/new-datasources/:id",
  SYNC_REPORTS: "/sync/reports",
  DATASOURCE_DETAILS: "/sync/datasources/:id",
  LIBRARY_ROOT: "/library",
  LIBRARY_BOOKS: "/library/books",
  LIBRARY_COLLECTIONS: "/library/collections",
  LIBRARY_SERIES: "/library/series",
  LIBRARY_TAGS: "/library/tags",
  TAG_BOOKS: "/library/tags/:id/books",
  COLLECTION_BOOKS: "/collections/:id/books",
  LOGIN: "/login",
  LOGIN_MAGIC_LINK: "/login/magic-link",
  SIGN_UP: "/signup",
  SIGN_UP_COMPLETE: "/signup/complete",
  READER: "/reader/:id",
  SEARCH: "/search",
  PROBLEMS: "/problems",
} as const
