version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "oboku-api"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-15kwd4lop27vd"
s3_prefix = "oboku-api"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
parameter_overrides = "JwtPrivateKey=JWT_PRIVATE_KEY"